"""Create Search Vector

Revision ID: 94b968abeadd
Revises: 86d0e3ba121b
Create Date: 2026-06-14 22:50:39.707464

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "94b968abeadd"
down_revision: Union[str, Sequence[str], None] = "86d0e3ba121b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "\n            setweight(to_tsvector('english', coalesce(name, '')), 'A')\n            || \n            setweight(to_tsvector('english', coalesce(description, '')), 'B')\n            ",
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.create_index("ix_products_tsv_gin", "products", ["tsv"], unique=False, postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_products_tsv_gin", table_name="products", postgresql_using="gin")
    op.drop_column("products", "tsv")
    # ### end Alembic commands ###
