"""Add datetime fields to product model

Revision ID: 86d0e3ba121b
Revises: 72e1efc4dcac
Create Date: 2026-06-14 18:51:39.007716

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "86d0e3ba121b"
down_revision: Union[str, Sequence[str], None] = "72e1efc4dcac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column(
        "products", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "updated_at")
    op.drop_column("products", "created_at")
    # ### end Alembic commands ###
